name: AWS CodeArtifact - Add NuGet Source
description: Adds a NuGet source to a nuget.config file
inputs:

  aws-region:
    description: The region of CodeArtifact domain.
    default: us-east-1
    required: true

  domain:
    description: The CodeArtifact domain name.
    default: d2l
    required: true

  repository:
    description: The CodeArtifact repository name.
    default: private
    required: true

  nuget-config-path:
    description: The NuGet config path.
    default: ./nuget.config
    required: true

  auth-token-duration-seconds:
    description: How long the CodeArtifact authorization token valid for in seconds.
    default: 900
    required: true

  role-arn:
    description: The IAM role arn to assume.
    required: false

runs:
  using: "composite"
  steps:

    - name: Get CodeArtifact Authorization Token & Repository endpoint
      id: codeartifact
      uses: ../../common/get-authorization-token-and-repository-endpoint
      with:
        auth-token-duration-seconds: ${{inputs.auth-token-duration-seconds}}
        aws-region: ${{inputs.aws-region}}
        domain: ${{inputs.domain}}
        repository: ${{inputs.repository}}
        repository-endpoint-format: nuget
        role-arn: ${{inputs.role-arn}}

    - name: Add CodeArtifact NuGet source
      shell: bash
      run: |
        if [ ! -f "${{inputs.nuget-config-path}}" ]; then
          echo "<configuration/>" >> "${{inputs.nuget-config-path}}"
        fi
        dotnet nuget add \
          source "${{steps.codeartifact.outputs.repository-endpoint}}v3/index.json" \
          --configfile "${{inputs.nuget-config-path}}" \
          --name "${{inputs.domain}}/${{inputs.repository}}" \
          --username aws \
          --password "${{steps.codeartifact.outputs.authorization-token}}" \
          --store-password-in-clear-text
