name: AWS CodeArtifact - Add NuGet Source
description: Adds a NuGet source to a nuget.config file
inputs:

  aws-region:
    description: The region of CodeArtifact domain.
    default: us-east-1
    required: true

  domain:
    description: The CodeArtifact domain name.
    default: d2l
    required: true

  repository:
    description: The CodeArtifact repository name.
    default: private
    required: true

  nuget-config-path:
    description: The NuGet config path.
    default: ./nuget.config
    required: true

  auth-token-duration-seconds:
    description: How long the CodeArtifact authorization token valid for in seconds.
    default: 900
    required: true

  role-arn:
    description: The IAM role arn to assume.
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
