name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - uses: Brightspace/third-party-actions@actions/checkout

      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: 12

      - name: nuget/add-source
        cwd: nuget/add-source
        run: npm run all

      - name: "Ensure no local changes from dist generation"
        run: git diff --exit-code
